import { Category, Product, Vehicle } from '@/types';

export const VEHICLES: Vehicle[] = [
  { id: 'v1', year: 2020, make: 'Audi', model: 'A4', engine: '2.0 TFSI' },
  { id: 'v2', year: 2018, make: 'BMW', model: '3 Series', engine: '320d' },
  { id: 'v3', year: 2022, make: 'Toyota', model: 'Rav4', engine: 'Hybrid 2.5' },
  { id: 'v4', year: 2019, make: 'Volkswagen', model: 'Golf', engine: '1.5 TSI' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Synthetic Gold 5W-30 Oil',
    brand: 'Castrol',
    price: 45.99,
    category: Category.Oils,
    rating: 4.8,
    reviews: 1240,
    imageUrl: 'https://picsum.photos/300/300?random=1',
    compatibleVehicles: ['v1', 'v2', 'v4'],
    stock: 50,
    tags: ['Best Seller', 'Winter Ready'],
    isPromo: true,
  },
  {
    id: 'p2',
    name: 'CleanAir Cabin Filter',
    brand: 'Bosch',
    price: 18.50,
    category: Category.Filters,
    rating: 4.6,
    reviews: 85,
    imageUrl: 'https://picsum.photos/300/300?random=2',
    compatibleVehicles: ['v1', 'v2', 'v3', 'v4'],
    stock: 200,
    tags: ['Activated Carbon'],
  },
  {
    id: 'p3',
    name: 'Aerotwin Wiper Set (Front)',
    brand: 'Bosch',
    price: 32.00,
    category: Category.Wipers,
    rating: 4.9,
    reviews: 432,
    imageUrl: 'https://picsum.photos/300/300?random=3',
    compatibleVehicles: ['v1', 'v4'],
    stock: 15,
    tags: ['Low Noise'],
  },
  {
    id: 'p4',
    name: 'Performance Oil Filter',
    brand: 'Mann-Filter',
    price: 12.99,
    category: Category.Filters,
    rating: 4.7,
    reviews: 210,
    imageUrl: 'https://picsum.photos/300/300?random=4',
    compatibleVehicles: ['v2', 'v3'],
    stock: 80,
  },
  {
    id: 'p5',
    name: 'Ceramic Brake Pads (Front)',
    brand: 'Brembo',
    price: 89.99,
    category: Category.Brakes,
    rating: 4.9,
    reviews: 65,
    imageUrl: 'https://picsum.photos/300/300?random=5',
    compatibleVehicles: ['v1', 'v2'],
    stock: 8,
    tags: ['High Performance'],
  },
  {
    id: 'p6',
    name: 'Dot 4 Brake Fluid (1L)',
    brand: 'Motul',
    price: 14.50,
    category: Category.Oils,
    rating: 4.5,
    reviews: 110,
    imageUrl: 'https://picsum.photos/300/300?random=6',
    compatibleVehicles: ['v1', 'v2', 'v3', 'v4'],
    stock: 120,
  },
  {
    id: 'p7',
    name: 'Hybrid Wiper Blade 24"',
    brand: 'Denso',
    price: 22.00,
    category: Category.Wipers,
    rating: 4.4,
    reviews: 56,
    imageUrl: 'https://picsum.photos/300/300?random=7',
    compatibleVehicles: ['v3'],
    stock: 45,
  },
];

export const FREE_SHIPPING_THRESHOLD = 100;