import Link from "next/link";
import Image from "next/image";
import { EnrichmentDetails } from "@/components/admin/enrichment-details";
import { EnrichmentRefresh } from "@/components/admin/enrichment-refresh";
import { ArrowDownToLine, ArrowUpRight, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Clock3, Database, ImageIcon, Layers3, Search, ShieldCheck, GitCompareArrows, CarFront } from "lucide-react";
import { requireAdmin } from "@/modules/auth/session";
import { enrichmentDashboard, enrichmentStatuses } from "@/modules/admin/enrichment-data";
import { passForecast } from "@/modules/admin/enrichment-pace";
import { normalizeSearchParams, type SearchParams } from "@/lib/search-params";
import { AdminPageHeader } from "@/components/admin/ui";
import "@/styles/enrichment-admin.css";

const pilotStatuses:Record<string,string>={prepared:"Hazır",running:"Çalışıyor",complete:"Bitti",blocked:"Kaynak nedeniyle durdu",stopped:"Durduruldu"};
const number=(value:number)=>new Intl.NumberFormat("tr-TR").format(value);
const date=(value:Date)=>new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(value);

export default async function ProductDataAdmin({searchParams}:{searchParams:Promise<SearchParams>}) {
  await requireAdmin();
  const data=await enrichmentDashboard(normalizeSearchParams(await searchParams));
  const counts=Object.fromEntries(data.counts.map(row=>[row.status,row.count]));
  const total=data.counts.reduce((sum,row)=>sum+row.count,0);
  const attempted=total-(counts.pending||0), attention=(counts.review||0)+(counts.blocked||0)+(counts.failed||0);
  const forecast=passForecast(data.pass,counts.pending||0);
  const days=(value:number|null)=>value===null?"—":value<1?"1 günden az":`~${number(Math.ceil(value))} gün`;
  const hours=(value:number)=>value.toLocaleString("tr-TR",{maximumFractionDigits:1});
  const sourceState=data.pass.blocked?"Kaynak bloke — koşu durdu":data.pass.challenge_since?`Cloudflare doğrulaması bekleniyor (${date(data.pass.challenge_since)} itibarıyla)`:"Kaynak erişilebilir";
  const href=(changes:Record<string,string>)=>{
    const params=new URLSearchParams({...data.filters,...changes});
    for(const [key,value] of [...params])if(!value||value==="all"||value==="enriched")params.delete(key);
    return `/yonetim/urun-verileri${params.size?`?${params}`:""}`;
  };
  const cards=[
    {label:"Zenginleştirilen ürün",value:data.metrics.enriched,icon:Layers3,note:`${number(counts.complete||0)} tamamlandı · ${number(counts.partial||0)} kısmi`,tone:"blue"},
    {label:"OEM referansıyla eşleşen",value:data.metrics.oem_matches,icon:GitCompareArrows,note:`${number(data.metrics.direct_matches)} doğrudan marka / parça eşleşmesi`,tone:"violet"},
    {label:"Araç / motor kaydı",value:data.metrics.vehicles,icon:CarFront,note:`${number(data.metrics.oem_numbers)} OEM referansı toplandı`,tone:"teal"},
    {label:"Görseli bulunan ürün",value:data.metrics.images,icon:ImageIcon,note:`${(Number(data.metrics.bytes)/1024/1024).toLocaleString("tr-TR",{maximumFractionDigits:1})} MB görsel depolanıyor`,tone:"amber"},
  ];
  return <section className="shell enrichment-admin">
    <AdminPageHeader breadcrumbs={[{label:"Yönetim",href:"/yonetim"},{label:"Ürün zenginleştirme"}]} eyebrow="Veri operasyonu" title="Ürün zenginleştirme" description="Parçaların bilgiye dönüşümünü tek yerden takip et." actions={<div className="enrichment-heading-actions"><span><span className="enrichment-live-dot"/>Veritabanından güncel görünüm</span><EnrichmentRefresh/></div>}/>
    <div className="enrichment-metrics">{cards.map(card=><article className={`enrichment-metric enrichment-${card.tone}`} key={card.label}><div><span>{card.label}</span><card.icon size={19}/></div><strong>{number(card.value)}</strong><small>{card.note}</small></article>)}</div>
    <div className="enrichment-overview"><article className="enrichment-progress"><div className="enrichment-section-heading"><h2>Katalog kapsamı</h2><span>{number(total)} ürün</span></div><div className="enrichment-progress-summary"><strong>{number(attempted)}<span> ürün incelendi</span></strong><span>{total?((attempted/total)*100).toLocaleString("tr-TR",{maximumFractionDigits:2}):0}%</span></div><div className="enrichment-progress-track" role="progressbar" aria-label="İncelenen ürünler" aria-valuenow={attempted} aria-valuemin={0} aria-valuemax={Math.max(total,1)}><span style={{width:`${total?attempted/total*100:0}%`}}/></div><div className="enrichment-progress-footer"><span><Clock3 size={14}/>{number(counts.pending||0)} ürün henüz incelenmedi</span><span>Son aktarım: {data.metrics.latest?date(data.metrics.latest):"Henüz yok"}</span></div></article>
      <Link href={href({status:"attention",match:"all",q:"",page:"1"})} className="enrichment-attention"><div className="enrichment-attention-icon"><CircleHelp size={22}/></div><div><span>Kontrol bekleyen kayıtlar</span><strong>{number(attention)}</strong><p>{number(counts.review||0)} inceleme · {number((counts.blocked||0)+(counts.failed||0))} erişim / işlem hatası</p></div><ArrowUpRight size={20}/></Link></div>
    <article className="enrichment-progress enrichment-pass"><div className="enrichment-section-heading"><h2>Katalog turu hızı</h2><span>Son 24 saat</span></div>
      <div className="enrichment-progress-summary"><strong>{number(data.pass.finished_24h)}<span> ürün arandı · çalışırken saatte {number(Math.round(forecast.perActiveHour))}</span></strong><span>{days(forecast.daysLeft)}</span></div>
      <p>Tarayıcı son 24 saatin {hours(forecast.activeHours)} saatinde çalıştı (%{Math.round(forecast.uptime*100)}). Kalan {number(counts.pending||0)} ürün bu hızla {days(forecast.daysLeft)}, kesintisiz çalışırsa {days(forecast.daysLeftAlwaysOn)} sürer.</p>
      <div className="enrichment-progress-footer"><span>{number(data.pass.linked_products)} ürün araç kataloğuna bağlı</span><span>{sourceState}{data.pass.interval_ms?` · istek aralığı ${hours(data.pass.interval_ms/1000)} sn`:""}</span></div></article>
    {data.pilot&&<article className="enrichment-progress enrichment-pilot"><div className="enrichment-section-heading"><h2>{number(data.pilot.sample_size)} ürünlük pilot</h2><span>{pilotStatuses[data.pilot.status]||data.pilot.status}</span></div><div className="enrichment-progress-summary"><strong>{number(data.pilot.processed)}<span> / {number(data.pilot.sample_size)} ürün işlendi</span></strong></div><div className="enrichment-progress-track" role="progressbar" aria-label="Pilot ürünleri" aria-valuenow={data.pilot.processed} aria-valuemin={0} aria-valuemax={data.pilot.sample_size}><span style={{width:`${data.pilot.processed/data.pilot.sample_size*100}%`}}/></div><p>{number(data.pilot.complete)} tamamlandı · {number(data.pilot.partial)} kısmi · {number(data.pilot.review)} inceleme · {number(data.pilot.not_found)} eşleşmeyen · {number(data.pilot.failed)} hata</p><div className="enrichment-progress-footer"><span>{number(data.pilot.requests)} kaynak isteği · {number(data.pilot.cache_hits)} önbellek kullanımı · {number(data.pilot.rate_limits)} hız sınırı yanıtı</span><span>{data.pilot.last_response?`Son kaynak yanıtı: ${date(data.pilot.last_response)}`:"Tarayıcı bağlantısı bekleniyor"}</span></div></article>}
    <article className="enrichment-results"><div className="enrichment-results-heading"><div><h2>Ürün kayıtları</h2><p>Eşleşmeleri ve veri kapsamını ürün bazında incele.</p></div><span>{number(data.total)} kayıt</span></div>
      <nav className="enrichment-tabs" aria-label="Zenginleştirme durumları">{[["enriched","Zenginleştirilen",data.metrics.enriched],["review","İnceleme",counts.review||0],["partial","Kısmi veri",counts.partial||0],["not_found","Eşleşmeyen",counts.not_found||0],["pending","Bekleyen",counts.pending||0]].map(([key,label,count])=><Link key={key} href={href({status:String(key),match:"all",page:"1"})} aria-current={data.filters.status===key?"page":undefined}>{label}<span>{number(Number(count))}</span></Link>)}</nav>
      <form key={`${data.filters.status}:${data.filters.match}:${data.filters.q}`} className="enrichment-filters" method="get"><label className="enrichment-search"><Search size={17}/><span className="sr-only">Ürün, marka veya OEM ara</span><input name="q" defaultValue={data.filters.q} placeholder="Ürün kodu, marka veya OEM ara…"/></label><label><span className="sr-only">Kayıt durumu</span><select name="status" defaultValue={data.filters.status}><option value="enriched">Zenginleştirilen ürünler</option><option value="attention">Kontrol bekleyen tüm kayıtlar</option>{Object.entries(enrichmentStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span className="sr-only">Eşleşme yöntemi</span><select name="match" defaultValue={data.filters.match}><option value="all">Tüm eşleşme yöntemleri</option><option value="oem_reference">OEM referansıyla</option><option value="exact_part">Doğrudan marka / parça</option></select></label><button type="submit">Filtrele</button>{(data.filters.q||data.filters.match!=="all")&&<Link href={href({q:"",match:"all",page:"1"})} className="enrichment-clear">Temizle</Link>}</form>
      {data.rows.length?<div className="enrichment-table-wrap" tabIndex={0} role="region" aria-label="Ürün zenginleştirme kayıtları"><table className="enrichment-table"><thead><tr><th>Ürün / tedarikçi kodu</th><th>Durum</th><th>Eşleşme</th><th>Toplanan veriler</th><th>Son işlem</th><th><span className="sr-only">Ayrıntılar</span></th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><td><div className="enrichment-product"><div className="enrichment-thumbnail">{row.image_id?<Image src={`/api/product-media/${row.image_id}`} alt="" width={40} height={40} sizes="40px" loading="lazy"/>:<ImageIcon size={20}/>}</div><div><Link href={`/urun/${row.id}`}>{row.name||row.code}</Link><span>{row.brand} <span className="enrichment-dot">·</span> <code>{row.code}</code></span></div></div></td><td><span className={`enrichment-status enrichment-status-${row.status}`}>{row.status==="complete"?<CheckCircle2 size={13}/>:row.status==="pending"?<Clock3 size={13}/>:null}{enrichmentStatuses[row.status]||row.status}</span></td><td>{row.match_type?<div className="enrichment-match"><span>{row.match_type==="oem_reference"?<GitCompareArrows size={14}/>:<ShieldCheck size={14}/>} {row.match_type==="oem_reference"?"OEM referansı":"Doğrudan eşleşme"}</span><small>{row.reference||`${row.manufacturer} ${row.manufacturer_part_number}`}</small></div>:<span className="enrichment-muted">Henüz doğrulanmadı</span>}</td><td><div className="enrichment-coverage"><span title="OEM referansı"><Database size={13}/><b>{number(row.oem_count)}</b> OEM</span><span title="Araç ve motor satırı"><CarFront size={13}/><b>{number(row.vehicle_count)}</b> araç</span><span title="Teknik özellik"><Layers3 size={13}/><b>{number(row.specification_count)}</b> özellik</span></div></td><td><time dateTime={(row.imported_at||row.updated_at).toISOString()}>{date(row.imported_at||row.updated_at)}</time><small className="enrichment-muted">{row.attempts} deneme</small></td><td><EnrichmentDetails name={row.name} code={row.code} productId={row.id} footer={<footer className="enrichment-modal-actions">{row.source_url?<a href={row.source_url} target="_blank" rel="noreferrer">{new URL(row.source_url).hostname}<ArrowUpRight size={14}/></a>:<span>Henüz kaynak verisi kaydedilmedi.</span>}<Link href={`/urun/${row.id}`}>Ürün sayfasını aç <ArrowUpRight size={14}/></Link></footer>}>
        <dl className="enrichment-modal-facts"><div><dt>Durum</dt><dd><span className={`enrichment-status enrichment-status-${row.status}`}>{enrichmentStatuses[row.status]||row.status}</span></dd></div><div><dt>Eşleşme yöntemi</dt><dd>{row.match_type==="oem_reference"?"OEM referansı":row.match_type==="exact_part"?"Doğrudan marka / parça":"Henüz doğrulanmadı"}</dd></div><div><dt>Referans ürün</dt><dd>{row.manufacturer?`${row.manufacturer} ${row.manufacturer_part_number}`:"Henüz yok"}</dd></div><div><dt>Tedarikçi OEM</dt><dd>{row.oem||"Belirtilmemiş"}</dd></div><div><dt>Görsel</dt><dd>{row.image_id?"Kaydedildi":"Henüz yok"}</dd></div><div><dt>Son işlem</dt><dd>{date(row.imported_at||row.updated_at)} · {row.attempts} deneme</dd></div></dl>
        <div className="enrichment-modal-coverage"><span><b>{number(row.oem_count)}</b> OEM referansı</span><span><b>{number(row.vehicle_count)}</b> araç / motor</span><span><b>{number(row.specification_count)}</b> teknik özellik</span></div>
        {row.last_error&&<p className="enrichment-modal-note">Son işlem notu: {row.last_error}</p>}

      </EnrichmentDetails></td></tr>)}</tbody></table></div>:<div className="enrichment-empty"><Search size={30}/><h3>Bu filtrelerle kayıt bulunamadı</h3><p>Arama kodunu veya eşleşme yöntemini değiştirerek tekrar dene.</p><Link href="/yonetim/urun-verileri">Tüm zenginleştirilen ürünler</Link></div>}
      <footer className="enrichment-pagination"><span>{data.total?`${number((data.page-1)*data.pageSize+1)}–${number(Math.min(data.page*data.pageSize,data.total))}`:"0"} / {number(data.total)} kayıt</span><div>{data.page>1?<Link href={href({page:String(data.page-1)})} aria-label="Önceki sayfa"><ChevronLeft size={16}/></Link>:<span aria-disabled="true"><ChevronLeft size={16}/></span>}<span>Sayfa {number(data.page)} / {number(data.pages)}</span>{data.page<data.pages?<Link href={href({page:String(data.page+1)})} aria-label="Sonraki sayfa"><ChevronRight size={16}/></Link>:<span aria-disabled="true"><ChevronRight size={16}/></span>}</div></footer>
    </article>
    <section className="enrichment-infrastructure"><div><h2>Veri kaynağı ve depolama</h2><p>Kaynak bağlantısının kontrol sonucu ile kaydedilmiş verileri ayrı takip et.</p></div><div className="enrichment-source-grid"><article><div className="enrichment-source-icon"><ArrowDownToLine size={19}/></div><div><h3>Kaynak erişimi</h3>{data.sources.map(source=><div key={source.host}><strong>{source.host}</strong><span className={`enrichment-status enrichment-status-${source.status==="blocked"?"review":"pending"}`}>{source.status==="blocked"?"Doğrudan erişim engelli":source.status==="accessible"?"Erişilebilir":"Bağlantı hatası"}</span><p>HTTP {source.http_status??"—"} · Kontrol: {date(source.checked_at)}</p></div>)}{!data.sources.length&&<p>Henüz kaynak kontrolü yapılmadı.</p>}<small>Bu sonuç doğrudan HTTP kontrolüne aittir. Tarayıcı üzerinden yapılan aktarımlar yukarıdaki kayıtlarda görünür.</small></div></article><article><div className="enrichment-source-icon"><Database size={19}/></div><div><h3>Veri ve görsel arşivi</h3><p><Check size={14}/>OEM, özellik ve araç bilgileri PostgreSQL’de</p><p><Check size={14}/>Görseller özel MinIO alanında</p><small>Tedarikçi marka, kod ve fiyat bilgileri kendi kaynağında korunur.</small></div></article></div></section>
  </section>;
}
