import {z} from "zod";
const values=z.array(z.string().trim().min(1).max(200)).max(30);
export const attributesSchema=z.record(z.string().min(1).max(200),values).refine(v=>Object.keys(v).length<=8);
export function selectedBrands(query:{brand?:string;brands?:string}):string[]{try{return query.brands?values.parse(JSON.parse(query.brands)):query.brand?[query.brand]:[];}catch{return [];}}
export function selectedAttributes(query:{attributes?:string}):Record<string,string[]>{try{return query.attributes?attributesSchema.parse(JSON.parse(query.attributes)):{};}catch{return {};}}
export type CatalogFacet={key:string;label:string;values:string[]};
const sourceIdentityFields=new Set(["Brand class","Manufacturer","Manufacturer Part Number","EAN","Trade numbers"]);
// An OEM alternative can supply technical criteria, but does not identify our manufacturer's part.
export function catalogSpecifications(specifications:[string,string][],exactPart:boolean){
 return exactPart?specifications:specifications.filter(([key])=>!sourceIdentityFields.has(key));
}
export function specificationLabel(key:string){return ({"Number of mounting bores":"Montaj deliği sayısı","Thickness [mm]":"Kalınlık [mm]","Bolt Hole Circle Ø [mm]":"Bijon dairesi çapı [mm]","Surface":"Yüzey","Minimum thickness [mm]":"Minimum kalınlık [mm]","Centering Diameter [mm]":"Merkezleme çapı [mm]","Number of Holes":"Delik sayısı","Fulfils ECE standard":"ECE standardı","Bore Diameter up to [mm]":"Maksimum delik çapı [mm]","Processing":"İşleme","Trade numbers":"Ticari numaralar","Rim Hole Number":"Bijon deliği sayısı","Manufacturer":"Üretici","Manufacturer Part Number":"Üretici parça numarası","Lamp Type":"Lamba tipi","Bulb Type":"Ampul tipi","Fuel Type":"Yakıt tipi","Shock Absorber Type":"Amortisör tipi","Shock Absorber System":"Amortisör sistemi","Wiper blade type":"Silecek tipi","Oil Viscosity Classification SAE":"Yağ viskozitesi SAE","Transmission Type":"Şanzıman tipi","Mounting Type":"Montaj tipi","Fitting Position":"Montaj konumu","Brake Disc Type":"Fren diski tipi","Outer Diameter [mm]":"Dış çap [mm]","Brake Disc Thickness [mm]":"Fren diski kalınlığı [mm]","Height [mm]":"Yükseklik [mm]","Brand class":"Marka sınıfı","Length [mm]":"Uzunluk [mm]","Width [mm]":"Genişlik [mm]","Filter type":"Filtre tipi","Thread Size":"Diş ölçüsü"} as Record<string,string>)[key]??key;}
export function specificationValue(value:string){return ({"internally vented":"İçten havalandırmalı","Coated":"Kaplamalı","High-carbon":"Yüksek karbonlu","Front Axle":"Ön aks","Rear Axle":"Arka aks","Front Axle Left":"Ön aks sol","Front Axle Right":"Ön aks sağ","Rear Axle Left":"Arka aks sol","Rear Axle Right":"Arka aks sağ","Front":"Ön","Rear":"Arka","Left":"Sol","Right":"Sağ","solid":"Dolu","Vented":"Havalandırmalı","vented":"Havalandırmalı","Premium":"Premium","Budget":"Ekonomik","Price/Performance":"Fiyat/Performans"} as Record<string,string>)[value]??value;}
