import { adminServiceAccounts } from "@/modules/admin/data";
import { normalizeSearchParams, type SearchParams } from "@/lib/search-params";
import { requireAdmin } from '@/modules/auth/session';
import { saveService } from '@/modules/admin/commerce-actions';
import { createService } from '@/modules/admin/actions';
export default async function Services({searchParams}:{searchParams:Promise<SearchParams>}) {
 await requireAdmin();const params=normalizeSearchParams(await searchParams);
 const accounts=await adminServiceAccounts();
 return <section className="shell page-section"><p className="eyebrow">B2B YÖNETİMİ</p><h1 className="page-title">Servis hesapları ve indirimler</h1><p className="muted">Her onaylı servis için satış fiyatına uygulanacak indirim oranını belirleyin. Değişiklik katalog ve sepete hemen yansır; geçmiş sipariş fiyatları korunur.</p>{(params.saved || params.created) && <p role="status" className="notice">Servis hesabı kaydedildi.</p>}{params.error && <p className="error" role="alert">Bilgileri kontrol edin. E-posta benzersiz, indirim %0–50 ve şifre en az 12 karakter ve en fazla 72 UTF-8 bayt olmalı.</p>}<div className="admin-columns"><div><h2>Mevcut servisler ({accounts.length})</h2>{accounts.map(a=><article key={a.id} className="panel"><h3>{a.name}</h3><p className="muted">{a.email}</p>{a.contact_name && <p>{a.contact_name} · {a.phone} · {a.city}</p>}<form action={saveService} className="stack"><input type="hidden" name="id" value={a.id}/><label>Özel indirim (%)<input name="discount" type="number" min={0} max={50} defaultValue={a.discount_percent} required/></label><label>Hesap durumu<select name="approved" defaultValue={String(a.approved)}><option value="true">Onaylı</option><option value="false">Pasif / Onay bekliyor</option></select></label><button>Servisi güncelle</button></form></article>)}</div><article className="panel"><h2>Yeni servis hesabı</h2><form action={createService} className="stack"><label>Servis adı<input name="name" minLength={2} maxLength={150} required/></label><label>E-posta<input type="email" name="email" maxLength={200} required/></label><label>İlk şifre<input type="password" name="password" minLength={12} maxLength={72} autoComplete="new-password" required/></label><label>Özel indirim (%)<input name="discount" type="number" min={0} max={50} defaultValue={0} required/></label><button>Onaylı servis oluştur</button></form></article></div></section>;
}
