/** Safely generate/apply/verify/rollback an immutable rpa-claude manifest. */
import { config } from 'dotenv'
config({ path: '.env.local' }); config({ path: '.env' })
import { createHash } from 'node:crypto'
import { mkdir, open, readFile, rename, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { Prisma } from '@prisma/client'
import { db } from '../lib/db'

const SITE='rpa-claude', ACTOR='bulk-apply-rpa-ref'
const args=process.argv.slice(2), opt=(n:string)=>args.find(a=>a.startsWith(`--${n}=`))?.slice(n.length+3)
interface Row { id:bigint; product_id:bigint; kind:string; value:string; value_norm:string; oem_brand:string; source_url:string|null; evidence:string|null; override_exists:boolean; name_override:string|null; selling_price_override:string|null; lock_price:boolean|null; category_override_id:number|null; note:string|null; override_updated_by:string|null; override_updated_at:Date|null }
interface P { suggestion_id:string; product_id:string; kind:string; value:string; value_norm:string; oem_brand:string; source_url:string|null; evidence:string|null; override_exists:boolean; name_override:string|null; selling_price_override:string|null; lock_price:boolean|null; category_override_id:number|null; note:string|null; override_updated_by:string|null; override_updated_at:string|null }
interface AppliedName { product_id:bigint; name_override:string|null; updated_by:string|null; updated_at:Date }
interface M { version:1; source_site:'rpa-claude'; initial_status:'PENDING'; cutoff_id:string; selected:P[]; oem_insertable:P[]; name_targets:P[] }
interface C { count:bigint }; interface X { max_id:bigint|null }
const sha=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex')
const p=(r:Row):P=>({suggestion_id:String(r.id),product_id:String(r.product_id),kind:r.kind,value:r.value,value_norm:r.value_norm,oem_brand:r.oem_brand,source_url:r.source_url,evidence:r.evidence,override_exists:r.override_exists,name_override:r.name_override,selling_price_override:r.selling_price_override===null?null:String(r.selling_price_override),lock_price:r.lock_price,category_override_id:r.category_override_id,note:r.note,override_updated_by:r.override_updated_by,override_updated_at:r.override_updated_at?.toISOString()??null})
const fk=(r:P)=>`${r.product_id}\0${r.value_norm}\0${r.oem_brand}`
function valid(v:unknown):M { const m=v as M
  if(!m||m.version!==1||m.source_site!==SITE||m.initial_status!=='PENDING'||!/^\d+$/.test(m.cutoff_id)||!Array.isArray(m.selected)||!Array.isArray(m.oem_insertable)||!Array.isArray(m.name_targets))throw Error('Manifest metadata/yapı geçersiz')
  const ids=m.selected.map(x=>BigInt(x.suggestion_id)); if(ids.some((x,i)=>x>BigInt(m.cutoff_id)||(i>0&&x<=ids[i-1])))throw Error('Selected ID sırası/unique/cutoff geçersiz')
  const byId=new Map(m.selected.map(x=>[x.suggestion_id,x])); for(const x of [...m.oem_insertable,...m.name_targets])if(JSON.stringify(x)!==JSON.stringify(byId.get(x.suggestion_id)))throw Error('Target payload selected ile uyuşmuyor')
  if(new Set(m.oem_insertable.map(fk)).size!==m.oem_insertable.length)throw Error('OEM final key unique değil')
  if(new Set(m.name_targets.map(x=>x.product_id)).size!==m.name_targets.length)throw Error('NAME target product unique değil')
  if(m.selected.some(x=>!['OEM','NAME'].includes(x.kind))||m.oem_insertable.some(x=>x.kind!=='OEM')||m.name_targets.some(x=>x.kind!=='NAME'))throw Error('Kind partition invariant geçersiz')
  return m }
async function load(path:string){const ap=resolve(path),b=await readFile(ap);return{path:ap,m:valid(JSON.parse(b.toString())),hash:sha(b)}}
function expected(actual:string){const e=opt('expected-sha256');if(!e||!/^\w{64}$/.test(e)||e.toLowerCase()!==actual)throw Error(`--expected-sha256 zorunlu/uyuşmalı; gerçek=${actual}`)}
async function durable(path:string,v:unknown){const h=await open(path,'wx');try{await h.writeFile(JSON.stringify(v,null,2)+'\n');await h.sync()}finally{await h.close()}}
const baseSelect=Prisma.sql`select s.id,s.product_id,s.kind,s.value,s.value_norm,s.oem_brand,s.source_url,s.evidence,
  (o.product_id is not null) as override_exists,o.name_override,o.selling_price_override,o.lock_price,o.category_override_id,o.note,
  o.updated_by as override_updated_by,o.updated_at as override_updated_at from catalog.product_ref_suggestions s left join catalog.product_overrides o on o.product_id=s.product_id`

async function generate(){const mx=await db.$queryRaw<X[]>`select max(id) max_id from catalog.product_ref_suggestions where source_site=${SITE} and status='PENDING' and kind in ('OEM','NAME')`;const cutoff=mx[0].max_id;if(!cutoff){console.log('PENDING yok');return}
  const rows=await db.$queryRaw<Row[]>(Prisma.sql`${baseSelect} where s.id<=${cutoff} and s.source_site=${SITE} and s.status='PENDING' and s.kind in ('OEM','NAME') order by s.id`)
  const oems=await db.$queryRaw<Row[]>(Prisma.sql`${baseSelect} where s.id<=${cutoff} and s.source_site=${SITE} and s.status='PENDING' and s.kind='OEM' and not exists(select 1 from catalog.product_oems x where x.product_id=s.product_id and x.code_norm=s.value_norm and x.oem_brand=s.oem_brand) order by s.id`)
  const seen=new Set<string>();const names=rows.filter(r=>r.kind==='NAME'&&!r.name_override?.trim()&&!seen.has(String(r.product_id))&&!!seen.add(String(r.product_id)))
  const m:M={version:1,source_site:SITE,initial_status:'PENDING',cutoff_id:String(cutoff),selected:rows.map(p),oem_insertable:oems.map(p),name_targets:names.map(p)};valid(m)
  const bytes=JSON.stringify(m,null,2)+'\n',path=resolve(opt('manifest')??`.data/reports/rpa-ref-apply-${cutoff}.json`);await mkdir(dirname(path),{recursive:true})
  await writeFile(path,bytes,{flag:'wx'}).catch(async(e:NodeJS.ErrnoException)=>{if(e.code!=='EEXIST')throw e;if(sha(await readFile(path))!==sha(bytes))throw Error('Mevcut manifest farklı')})
  console.log(`DRY-RUN selected=${rows.length} OEM=${oems.length} NAME=${names.length}\n${path}\nSHA-256: ${sha(bytes)}`)}

async function apply(path:string){const a=await load(path);expected(a.hash);const m=a.m,ids=m.selected.map(x=>BigInt(x.suggestion_id)),oi=m.oem_insertable.map(x=>BigInt(x.suggestion_id)),ni=m.name_targets.map(x=>BigInt(x.suggestion_id));const receipt=`${a.path}.receipt.json`,prepared={state:'PREPARED',manifest_sha256:a.hash,selected_count:m.selected.length,inserted_oem_keys:m.oem_insertable,name_rows:m.name_targets};await durable(receipt,prepared)
  const result=await db.$transaction(async tx=>{const live=await tx.$queryRaw<Row[]>(Prisma.sql`${baseSelect} where s.id<=${BigInt(m.cutoff_id)} and s.source_site=${SITE} and s.status='PENDING' and s.kind in ('OEM','NAME') order by s.id for update of s`);if(JSON.stringify(live.map(p))!==JSON.stringify(m.selected))throw Error('Canlı PENDING kümesi/payload/override değişti')
    const productIds=[...new Set(m.name_targets.map(x=>BigInt(x.product_id)))];if(productIds.length)await tx.$queryRaw`select product_id from catalog.product_overrides where product_id=any(${productIds}) for update`
    const ins=oi.length?await tx.$executeRaw`insert into catalog.product_oems(product_id,code,code_norm,oem_brand,source) select product_id,value,value_norm,oem_brand,'WEB' from catalog.product_ref_suggestions where id=any(${oi}) order by id on conflict(product_id,code_norm,oem_brand) do nothing`:0;if(ins!==oi.length)throw Error('OEM insert count değişti')
    const names=ni.length?await tx.$queryRaw<AppliedName[]>`insert into catalog.product_overrides(product_id,name_override,updated_by) select product_id,value,${ACTOR} from catalog.product_ref_suggestions where id=any(${ni}) order by id on conflict(product_id) do update set name_override=excluded.name_override,updated_by=excluded.updated_by,updated_at=current_timestamp where catalog.product_overrides.name_override is null or btrim(catalog.product_overrides.name_override)='' returning product_id,name_override,updated_by,updated_at`:[];if(names.length!==ni.length)throw Error('NAME count değişti')
    const upd=await tx.$executeRaw`update catalog.product_ref_suggestions set status='APPLIED',reviewed_by=${ACTOR},reviewed_at=current_timestamp,applied_at=current_timestamp where id=any(${ids}) and status='PENDING'`;if(upd!==ids.length)throw Error('Suggestion update count değişti');return{ins,name_count:names.length,upd,names:names.map(x=>({product_id:String(x.product_id),name_override:x.name_override,updated_by:x.updated_by,updated_at:x.updated_at.toISOString()}))}}, {isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:900000,maxWait:30000})
  const tmp=`${receipt}.tmp-${process.pid}`;await durable(tmp,{...prepared,state:'COMMITTED',committed_at:new Date().toISOString(),counts:{oem:result.ins,names:result.name_count,suggestions:result.upd},name_applied_rows:result.names});await rename(tmp,receipt);console.log(`COMMITTED OEM=${result.ins} NAME=${result.name_count} suggestions=${result.upd}`)}

async function check(path:string){const a=await load(path);expected(a.hash);const m=a.m,ids=m.selected.map(x=>BigInt(x.suggestion_id)),oi=m.oem_insertable.map(x=>BigInt(x.suggestion_id)),ni=m.name_targets.map(x=>BigInt(x.suggestion_id));const [ap,pd,out,okOem,okName]=await Promise.all([db.$queryRaw<C[]>`select count(*) count from catalog.product_ref_suggestions where id=any(${ids}) and status='APPLIED' and reviewed_by=${ACTOR}`,db.$queryRaw<C[]>`select count(*) count from catalog.product_ref_suggestions where id=any(${ids}) and status='PENDING'`,db.$queryRaw<C[]>`select count(*) count from catalog.product_ref_suggestions where id<=${BigInt(m.cutoff_id)} and source_site=${SITE} and kind in ('OEM','NAME') and status='PENDING' and not(id=any(${ids}))`,oi.length?db.$queryRaw<C[]>`select count(*) count from catalog.product_oems o join catalog.product_ref_suggestions s on s.id=any(${oi}) and o.product_id=s.product_id and o.code_norm=s.value_norm and o.oem_brand=s.oem_brand where o.source='WEB'`:Promise.resolve([{count:BigInt(0)}]),ni.length?db.$queryRaw<C[]>`select count(*) count from catalog.product_overrides o join catalog.product_ref_suggestions s on s.id=any(${ni}) and o.product_id=s.product_id and o.name_override=s.value where o.updated_by=${ACTOR}`:Promise.resolve([{count:BigInt(0)}])]);const result={applied:Number(ap[0].count),pending:Number(pd[0].count),outside:Number(out[0].count),oem:Number(okOem[0].count),names:Number(okName[0].count)};console.log(result);if(result.applied!==ids.length||result.pending!==0||result.outside!==0||result.oem!==oi.length||result.names!==ni.length)throw Error('Post-check başarısız')}

async function rollback(path:string){const a=await load(path);expected(a.hash);const m=a.m,r=JSON.parse(await readFile(`${a.path}.receipt.json`,'utf8'));if(!['PREPARED','COMMITTED'].includes(r.state)||r.manifest_sha256!==a.hash)throw Error('Receipt geçersiz');const ids=m.selected.map(x=>BigInt(x.suggestion_id)),oi=m.oem_insertable.map(x=>BigInt(x.suggestion_id)),ni=m.name_targets.map(x=>BigInt(x.suggestion_id)),np=m.name_targets.map(x=>BigInt(x.product_id));const [ap,okOem,okName]=await Promise.all([db.$queryRaw<C[]>`select count(*) count from catalog.product_ref_suggestions where id=any(${ids}) and status='APPLIED' and reviewed_by=${ACTOR}`,oi.length?db.$queryRaw<C[]>`select count(*) count from catalog.product_oems o join catalog.product_ref_suggestions s on s.id=any(${oi}) and o.product_id=s.product_id and o.code_norm=s.value_norm and o.oem_brand=s.oem_brand where o.source='WEB'`:Promise.resolve([{count:BigInt(0)}]),ni.length?db.$queryRaw<C[]>`select count(*) count from catalog.product_overrides o join catalog.product_ref_suggestions s on s.id=any(${ni}) and o.product_id=s.product_id and o.name_override=s.value where o.updated_by=${ACTOR}`:Promise.resolve([{count:BigInt(0)}])]);if(Number(ap[0].count)!==ids.length||Number(okOem[0].count)!==oi.length||Number(okName[0].count)!==ni.length)throw Error('Rollback precheck başarısız');if(!args.includes('--confirm-rollback')){console.log(`ROLLBACK DRY-RUN selected=${ids.length} OEM=${oi.length} NAME=${np.length}`);return}
  await db.$transaction(async tx=>{const lockedSuggestions=await tx.$queryRaw<Array<{id:bigint}>>`select id from catalog.product_ref_suggestions where id=any(${ids}) and status='APPLIED' and reviewed_by=${ACTOR} order by id for update`;if(lockedSuggestions.length!==ids.length)throw Error('Rollback suggestion state değişti');const lockedNames=np.length?await tx.$queryRaw<Array<{product_id:bigint;name_override:string|null;updated_by:string|null}>>`select product_id,name_override,updated_by from catalog.product_overrides where product_id=any(${np}) order by product_id for update`:[];if(lockedNames.length!==np.length||lockedNames.some(row=>row.updated_by!==ACTOR||row.name_override!==m.name_targets.find(x=>x.product_id===String(row.product_id))?.value))throw Error('Rollback NAME state değişti');const d=oi.length?await tx.$executeRaw`delete from catalog.product_oems o using catalog.product_ref_suggestions s where s.id=any(${oi}) and o.product_id=s.product_id and o.code_norm=s.value_norm and o.oem_brand=s.oem_brand and o.source='WEB'`:0;if(d!==oi.length)throw Error('OEM rollback count')
    let n=0;for(const x of m.name_targets){if(x.override_exists)n+=await tx.$executeRaw`update catalog.product_overrides set name_override=${x.name_override},updated_by=${x.override_updated_by},updated_at=${x.override_updated_at ? new Date(x.override_updated_at) : new Date(0)} where product_id=${BigInt(x.product_id)} and updated_by=${ACTOR} and name_override=${x.value}`;else{const d=await tx.$executeRaw`delete from catalog.product_overrides where product_id=${BigInt(x.product_id)} and updated_by=${ACTOR} and name_override=${x.value} and selling_price_override is null and lock_price=false and category_override_id is null and note is null`;n+=d;if(d===0)n+=await tx.$executeRaw`update catalog.product_overrides set name_override=null,updated_by=null,updated_at=current_timestamp where product_id=${BigInt(x.product_id)} and updated_by=${ACTOR} and name_override=${x.value}`}};if(n!==np.length)throw Error('NAME rollback count')
    const u=await tx.$executeRaw`update catalog.product_ref_suggestions set status='PENDING',reviewed_by=null,reviewed_at=null,applied_at=null where id=any(${ids}) and status='APPLIED' and reviewed_by=${ACTOR}`;if(u!==ids.length)throw Error('Suggestion rollback count')},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:900000,maxWait:30000})}

async function main(){if(args.includes('--apply'))throw Error('--apply-manifest kullanın');const ap=opt('apply-manifest'),pc=opt('post-check'),rb=opt('rollback-manifest');if([ap,pc,rb].filter(Boolean).length>1)throw Error('Tek mod seçin');if(ap)return apply(ap);if(pc)return check(pc);if(rb)return rollback(rb);return generate()}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect())
